remote_theme: daattali/beautiful-jekyll
# theme: jekyll-theme-minimal
language: zh-tw
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
