remote_theme: pages-themes/slate@v0.2.0

# theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
