remote_theme: mmistakes/minimal-mistakes

# theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
