remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll
# theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
