layout: page
remote_theme: daattali/beautiful-jekyll


plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  
language: zh-Hant-TW
gh-repo: uol-taiwan/resource-hub
gh-badge: follow
nav-short: true
