layout: page
remote_theme: daattali/beautiful-jekyll
nav-short: true
# theme: jekyll-theme-minimal
language: zh-Hant-TW
gh-repo: uol-taiwan/resource-hub
gh-badge: follow
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
