---
remote_theme: daattali/beautiful-jekyll
layout: page

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

navbar-links:
  "最新消息": "newest_uploads.html"

language: zh-Hant-TW
title: UOL Taiwan
avatar: "/assets/images/ULTSG_Logo.png"
gh-repo: uol-taiwan/resource-hub
gh-badge: start
nav-short: true
baseurl: /resource-hub

site-css:
  - /assets/css/custom.css

site-js:
  - /assets/js/custom.js
  - /assets/js/widget.js
  - /assets/js/countdown.js

include:
  - README.md
  - /assets/css/custom.css
  - /assets/js/custom.js
  - /assets/js/widget.js
  - /assets/js/countdown.js
---

