remote_theme: daattali/beautiful-jekyll
layout: page
language: zh-Hant-TW
gh-repo: uol-taiwan/resource-hub
gh-badge: follow
nav-short: true

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md

title-heading: false
css: "/Styles/style.css"
font-family: 'Helvetica Neue', 'Helvetica', 'Microsoft Yahei', sans-serif;