---
remote_theme: daattali/beautiful-jekyll
layout: page

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  
navbar-links:
  "新同學": "For New Students.html"
  "加入 Discord": https://discord.gg/naaSD4yxtK
  
language: zh-Hant-TW
title: UOL Taiwan
avatar: "ULTSG_Logo.png"
gh-repo: uol-taiwan/resource-hub
gh-badge: start
nav-short: true
baseurl: /resource-hub

# head-extra:
#   - <link rel="stylesheet" href="./assets/css/style.css">
#   - <script src="./assets/js/index.js"
  
site-css:
  - "/assets/css/custom.css"

site-js:
  - "/assets/js/custom.js"

include:
  - README.md
  - /assets/css/custom.css
  - /assets/js/custom.js




  # - /assets/css/style.scss
  # - /assets/js/index.js
# title-heading: false

# css: /assets/css/style.scss
# js: /assets/js/index.js



# font-family:
#   - Helvetica Neue
#   - Helvetica
#   - Microsoft Yahei
#   - sans-serif
# defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "default"
---

