---
remote_theme: daattali/beautiful-jekyll
layout: minimal

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  # - /assets/css/style.scss
  # - /assets/js/index.js
# title-heading: false

# css: /assets/css/style.scss
# js: /assets/js/index.js

author:
  name: UOL Taiwan
  github: uol-taiwan  

navbar-links:
  "For New Students": "For New Students.html"
  
language: zh-Hant-TW
title: UOL Taiwan
avatar: "ULTSG_Logo.png"
gh-repo: uol-taiwan/resource-hub
gh-badge: start
nav-short: true
baseurl: /resource-hub
css: "style.css"

footer-links-active:
  github: true

head-extra:
  - <link rel="stylesheet" href="./assets/css/style.css">
  - <script src="./assets/js/index.js"

# font-family:
#   - Helvetica Neue
#   - Helvetica
#   - Microsoft Yahei
#   - sans-serif
# defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "default"
---

