---
remote_theme: daattali/beautiful-jekyll
layout: page
language: zh-Hant-TW
gh-repo: uol-taiwan/resource-hub
gh-badge: follow
nav-short: true
baseurl: /resource-hub

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - /assets/css/style.scss
  - /assets/js/index.js
title-heading: false
css: /resource-hub/assets/css/style.scss
js: /assets/js/index.js
font-family:
  - Helvetica Neue
  - Helvetica
  - Microsoft Yahei
  - sans-serif
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
---

